version: "3.9"
services:
  api:
    build: .
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 1"
    volumes:
      - .:/ucb-api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
