name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          architecture: x64

      - name: Prepare Environement
        shell: bash
        run: pip install -U pip
          pip install poetry
          poetry config --local
          poetry --version

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Coverage reports
        shell: bash
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m
          poetry run coverage html -d ${{ github.workspace }}/htmlcov

      - name: Create html coverage report
        shell: bash
        run: poetry run coverage html

      - name: "Upload HTML report"
        uses: actions/upload-artifact@v3
        with:
          path: htmlcov

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/htmlcov
